version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      dev:
        applies-to: 'version-updates'
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'

      prod:
        applies-to: 'version-updates'
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'

      security:
        applies-to: 'security-updates'

    # Schedule run every Thursday, local time
    schedule:
      interval: weekly
      day: 'thursday'
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Thursday, local time
    schedule:
      interval: weekly
      day: 'thursday'
      time: '10:30'
      timezone: 'Europe/London'
