services:
  cdp-defra-id-stub:
    depends_on:
      redis:
        condition: service_started
    environment:
      APP_BASE_URL: http://localhost:3200
      NODE_ENV: development
      OIDC_BASE_PATH: /cdp-defra-id-stub
      OIDC_CLIENT_ID: 63983fc2-cfff-45bb-8ec2-959e21062b9a
      OIDC_CLIENT_SECRET: test_value
      OIDC_SHOW_LOGIN: true
      PORT: 3200
      REDIS_HOST: redis
      SESSION_CACHE_ENGINE: redis
      USE_SINGLE_INSTANCE_CACHE: true
    image: defradigital/cdp-defra-id-stub:${DEFRA_ID_STUB_VERSION:-latest}
    networks:
      - cdp-tenant
    ports:
      - '3200:3200'
    profiles:
      - stub

  cdp-uploader:
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      CONSUMER_BUCKETS: re-ex-summary-logs
      MOCK_VIRUS_RESULT_DELAY: 3
      MOCK_VIRUS_SCAN_ENABLED: true
      NODE_ENV: development
      PORT: 7337
      REDIS_HOST: redis
      S3_ENDPOINT: http://localstack:4566
      SQS_ENDPOINT: http://localstack:4566
      USE_SINGLE_INSTANCE_CACHE: true
      VIRTUAL_HOST: ~^uploader\..*\.sslip\.io
      VIRTUAL_PATH: /
      VIRTUAL_PORT: 7337
    image: defradigital/cdp-uploader:${CDP_UPLOADER_VERSION:-latest}
    networks:
      - cdp-tenant
    ports:
      - '7337:7337'

  localstack:
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LOCALSTACK_HOST: 127.0.0.1
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
    healthcheck:
      test: ['CMD', 'stat', '/tmp/READY']
      interval: 3s
      start_period: 5s
      retries: 20
    image: localstack/localstack:3.0.2
    networks:
      - cdp-tenant
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - './compose:/etc/localstack/init/ready.d'

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - mongodb-data:/data
      - ./mongodb-backups:/backups

  proxy:
    environment:
      - ENABLE_IPV6=true
      - DEFAULT_ROOT="418"
      - DEFAULT_HOST=~^uploader\..*\.sslip\.io
    image: nginxproxy/nginx-proxy:1.4
    networks:
      - cdp-tenant
    ports:
      - '7300:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  redis:
    image: redis:7.2.11-alpine3.21
    networks:
      - cdp-tenant
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
