import { describe, expect, it } from 'vitest'

import { VALIDATION_CODE } from './validation.js'

describe('VALIDATION_CODE enum', () => {
  it('should mirror the full backend validation-code set', () => {
    expect(VALIDATION_CODE).toStrictEqual({
      REGISTRATION_REQUIRED: 'REGISTRATION_REQUIRED',
      MATERIAL_REQUIRED: 'MATERIAL_REQUIRED',
      PROCESSING_TYPE_REQUIRED: 'PROCESSING_TYPE_REQUIRED',
      PROCESSING_TYPE_INVALID: 'PROCESSING_TYPE_INVALID',
      TEMPLATE_VERSION_REQUIRED: 'TEMPLATE_VERSION_REQUIRED',
      TEMPLATE_VERSION_INVALID: 'TEMPLATE_VERSION_INVALID',
      REGISTRATION_DATA_INVALID: 'REGISTRATION_DATA_INVALID',
      REGISTRATION_MISMATCH: 'REGISTRATION_MISMATCH',
      PROCESSING_TYPE_DATA_INVALID: 'PROCESSING_TYPE_DATA_INVALID',
      PROCESSING_TYPE_MISMATCH: 'PROCESSING_TYPE_MISMATCH',
      MATERIAL_DATA_INVALID: 'MATERIAL_DATA_INVALID',
      MATERIAL_MISMATCH: 'MATERIAL_MISMATCH',
      ACCREDITATION_MISSING: 'ACCREDITATION_MISSING',
      ACCREDITATION_MISMATCH: 'ACCREDITATION_MISMATCH',
      ACCREDITATION_UNEXPECTED: 'ACCREDITATION_UNEXPECTED',
      TABLE_UNRECOGNISED: 'TABLE_UNRECOGNISED',
      HEADER_REQUIRED: 'HEADER_REQUIRED',
      FIELD_REQUIRED: 'FIELD_REQUIRED',
      INVALID_TYPE: 'INVALID_TYPE',
      VALUE_OUT_OF_RANGE: 'VALUE_OUT_OF_RANGE',
      INVALID_FORMAT: 'INVALID_FORMAT',
      INVALID_DATE: 'INVALID_DATE',
      CALCULATED_VALUE_MISMATCH: 'CALCULATED_VALUE_MISMATCH',
      SEQUENTIAL_ROW_REMOVED: 'SEQUENTIAL_ROW_REMOVED',
      MUST_BE_A_NUMBER: 'MUST_BE_A_NUMBER',
      MUST_BE_A_STRING: 'MUST_BE_A_STRING',
      MUST_BE_A_VALID_DATE: 'MUST_BE_A_VALID_DATE',
      MUST_BE_GREATER_THAN_ZERO: 'MUST_BE_GREATER_THAN_ZERO',
      MUST_BE_AT_LEAST_ZERO: 'MUST_BE_AT_LEAST_ZERO',
      MUST_BE_LESS_THAN_1: 'MUST_BE_LESS_THAN_1',
      MUST_BE_AT_MOST_1: 'MUST_BE_AT_MOST_1',
      MUST_BE_AT_MOST_1000: 'MUST_BE_AT_MOST_1000',
      MUST_BE_AT_MOST_100_CHARS: 'MUST_BE_AT_MOST_100_CHARS',
      MUST_BE_YES_OR_NO: 'MUST_BE_YES_OR_NO',
      MUST_CONTAIN_ONLY_PERMITTED_CHARACTERS:
        'MUST_CONTAIN_ONLY_PERMITTED_CHARACTERS',
      MUST_BE_3_DIGIT_ID: 'MUST_BE_3_DIGIT_ID',
      MUST_BE_VALID_EWC_CODE: 'MUST_BE_VALID_EWC_CODE',
      MUST_BE_VALID_RECYCLABLE_PROPORTION_METHOD:
        'MUST_BE_VALID_RECYCLABLE_PROPORTION_METHOD',
      MUST_BE_VALID_WASTE_DESCRIPTION: 'MUST_BE_VALID_WASTE_DESCRIPTION',
      MUST_BE_VALID_BASEL_CODE: 'MUST_BE_VALID_BASEL_CODE',
      MUST_BE_VALID_EXPORT_CONTROL: 'MUST_BE_VALID_EXPORT_CONTROL',
      NET_WEIGHT_CALCULATION_MISMATCH: 'NET_WEIGHT_CALCULATION_MISMATCH',
      TONNAGE_CALCULATION_MISMATCH: 'TONNAGE_CALCULATION_MISMATCH',
      UK_PACKAGING_PROPORTION_CALCULATION_MISMATCH:
        'UK_PACKAGING_PROPORTION_CALCULATION_MISMATCH',
      FILE_VIRUS_DETECTED: 'FILE_VIRUS_DETECTED',
      FILE_EMPTY: 'FILE_EMPTY',
      FILE_TOO_LARGE: 'FILE_TOO_LARGE',
      FILE_WRONG_TYPE: 'FILE_WRONG_TYPE',
      FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
      FILE_DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',
      FILE_REJECTED: 'FILE_REJECTED',
      SPREADSHEET_INVALID_ERROR: 'SPREADSHEET_INVALID_ERROR',
      SPREADSHEET_MALFORMED_MARKERS: 'SPREADSHEET_MALFORMED_MARKERS',
      VALIDATION_FALLBACK_ERROR: 'VALIDATION_FALLBACK_ERROR',
      VALIDATION_SYSTEM_ERROR: 'VALIDATION_SYSTEM_ERROR'
    })
  })

  it('should be frozen', () => {
    expect(Object.isFrozen(VALIDATION_CODE)).toBe(true)
  })
})
