// copied from matching file in epr-backend - keep in sync (as much as we need)

/**
 * Valid PROCESSING_TYPE values that can appear in summary log spreadsheets
 */
export const PROCESSING_TYPES = Object.freeze({
  REPROCESSOR_INPUT: 'REPROCESSOR_INPUT',
  REPROCESSOR_OUTPUT: 'REPROCESSOR_OUTPUT',
  EXPORTER: 'EXPORTER',
  REGISTERED_ONLY_REPROCESSOR: 'REPROCESSOR_REGISTERED_ONLY',
  REGISTERED_ONLY_EXPORTER: 'EXPORTER_REGISTERED_ONLY'
})

/** @typedef {typeof PROCESSING_TYPES[keyof typeof PROCESSING_TYPES]} ProcessingType */

export const REGISTERED_ONLY_PROCESSING_TYPES = new Set(
  PROCESSING_TYPES.REGISTERED_ONLY_REPROCESSOR,
  PROCESSING_TYPES.REGISTERED_ONLY_EXPORTER
)
