/**
 * Validation failure codes from backend API
 * Must match codes in epr-backend/src/common/enums/validation.js
 */
export const validationFailureCodes = Object.freeze({
  // File upload failures (CDP uploader rejections)
  FILE_DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',
  FILE_EMPTY: 'FILE_EMPTY',
  FILE_REJECTED: 'FILE_REJECTED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_VIRUS_DETECTED: 'FILE_VIRUS_DETECTED',
  FILE_WRONG_TYPE: 'FILE_WRONG_TYPE',

  // Meta-level syntax failures
  HEADER_REQUIRED: 'HEADER_REQUIRED',
  TEMPLATE_VERSION_INVALID: 'TEMPLATE_VERSION_INVALID',
  TEMPLATE_VERSION_REQUIRED: 'TEMPLATE_VERSION_REQUIRED',
  PROCESSING_TYPE_INVALID: 'PROCESSING_TYPE_INVALID',
  PROCESSING_TYPE_REQUIRED: 'PROCESSING_TYPE_REQUIRED',

  // Meta-level business failures
  REGISTRATION_DATA_INVALID: 'REGISTRATION_DATA_INVALID',
  REGISTRATION_MISMATCH: 'REGISTRATION_MISMATCH',
  REGISTRATION_REQUIRED: 'REGISTRATION_REQUIRED',
  ACCREDITATION_MISMATCH: 'ACCREDITATION_MISMATCH',
  ACCREDITATION_MISSING: 'ACCREDITATION_MISSING',
  ACCREDITATION_UNEXPECTED: 'ACCREDITATION_UNEXPECTED',
  MATERIAL_DATA_INVALID: 'MATERIAL_DATA_INVALID',
  MATERIAL_MISMATCH: 'MATERIAL_MISMATCH',
  MATERIAL_REQUIRED: 'MATERIAL_REQUIRED',
  PROCESSING_TYPE_DATA_INVALID: 'PROCESSING_TYPE_DATA_INVALID',
  PROCESSING_TYPE_MISMATCH: 'PROCESSING_TYPE_MISMATCH',

  // Data-level failures (row/cell validation)
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  INVALID_TYPE: 'INVALID_TYPE',
  VALUE_OUT_OF_RANGE: 'VALUE_OUT_OF_RANGE',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_DATE: 'INVALID_DATE',
  ROW_ID_MISMATCH: 'ROW_ID_MISMATCH',
  SEQUENTIAL_ROW_REMOVED: 'SEQUENTIAL_ROW_REMOVED',
  TABLE_UNRECOGNISED: 'TABLE_UNRECOGNISED',

  // System/fallback
  VALIDATION_SYSTEM_ERROR: 'VALIDATION_SYSTEM_ERROR',
  UNKNOWN: 'UNKNOWN'
})

/**
 * Data entry codes that map to a generic user message
 * These are cell/row validation failures that users can fix by correcting spreadsheet data
 */
export const DATA_ENTRY_CODES = new Set([
  validationFailureCodes.FIELD_REQUIRED,
  validationFailureCodes.INVALID_TYPE,
  validationFailureCodes.VALUE_OUT_OF_RANGE,
  validationFailureCodes.INVALID_FORMAT,
  validationFailureCodes.INVALID_DATE
])

/**
 * Display code for grouped data entry errors
 */
export const DATA_ENTRY_DISPLAY_CODE = 'DATA_ENTRY_INVALID'
