export const TECHNICAL_ERROR_DISPLAY_CODE = 'TECHNICAL_ERROR'

const CALCULATED_ERROR_CODES = new Set([
  'NET_WEIGHT_CALCULATION_MISMATCH',
  'TONNAGE_CALCULATION_MISMATCH',
  'UK_PACKAGING_PROPORTION_CALCULATION_MISMATCH'
])

const CALCULATED_HEADERS = new Set([
  'NET_WEIGHT',
  'TONNAGE_RECEIVED_FOR_RECYCLING',
  'TONNAGE_RECEIVED_FOR_EXPORT',
  'PRODUCT_UK_PACKAGING_WEIGHT_PROPORTION'
])

const PERCENTAGE_ERROR_CODES = new Set([
  'MUST_BE_A_NUMBER',
  'MUST_BE_AT_LEAST_ZERO',
  'MUST_BE_LESS_THAN_1',
  'MUST_BE_AT_MOST_1'
])

const PERCENTAGE_HEADERS = new Set([
  'RECYCLABLE_PROPORTION_PERCENTAGE',
  'UK_PACKAGING_WEIGHT_PERCENTAGE'
])

const WEIGHT_ERROR_CODES = new Set([
  'MUST_BE_A_NUMBER',
  'MUST_BE_GREATER_THAN_ZERO',
  'MUST_BE_AT_LEAST_ZERO',
  'MUST_BE_AT_MOST_1000'
])

const WEIGHT_HEADERS = new Set([
  'GROSS_WEIGHT',
  'TARE_WEIGHT',
  'PALLET_WEIGHT',
  'NET_WEIGHT',
  'WEIGHT_OF_NON_TARGET_MATERIALS',
  'TONNAGE_PASSED_INTERIM_SITE_RECEIVED_BY_OSR',
  'PRODUCT_TONNAGE',
  'TONNAGE_RECEIVED_FOR_RECYCLING',
  'TONNAGE_RECEIVED_FOR_EXPORT',
  'PRODUCT_UK_PACKAGING_WEIGHT_PROPORTION',
  'TONNAGE_OF_UK_PACKAGING_WASTE_EXPORTED',
  'TONNAGE_OF_UK_PACKAGING_WASTE_SENT_ON'
])

const DATE_ERROR_CODES = new Set(['MUST_BE_A_VALID_DATE'])

const DATE_HEADERS = new Set([
  'DATE_LOAD_LEFT_SITE',
  'DATE_RECEIVED_FOR_REPROCESSING',
  'DATE_RECEIVED_FOR_EXPORT',
  'DATE_OF_EXPORT'
])

const YES_NO_ERROR_CODES = new Set(['MUST_BE_YES_OR_NO', 'MUST_BE_A_STRING'])

const YES_NO_HEADERS = new Set([
  'ADD_PRODUCT_WEIGHT',
  'WERE_PRN_OR_PERN_ISSUED_ON_THIS_WASTE',
  'BAILING_WIRE_PROTOCOL',
  'DID_WASTE_PASS_THROUGH_AN_INTERIM_SITE'
])

const DROPDOWN_ERROR_CODES = new Set([
  'MUST_BE_VALID_RECYCLABLE_PROPORTION_METHOD',
  'MUST_BE_VALID_EWC_CODE',
  'MUST_BE_VALID_BASEL_CODE',
  'MUST_BE_VALID_WASTE_DESCRIPTION',
  'MUST_BE_VALID_EXPORT_CONTROL',
  'MUST_BE_A_STRING'
])

const DROPDOWN_HEADERS = new Set([
  'HOW_DID_YOU_CALCULATE_RECYCLABLE_PROPORTION',
  'DESCRIPTION_WASTE',
  'EWC_CODE',
  'BASEL_EXPORT_CODE',
  'EXPORT_CONTROLS'
])

const FREE_TEXT_ERROR_CODES = new Set([
  'MUST_BE_ALPHANUMERIC',
  'MUST_BE_AT_MOST_100_CHARS'
])

const FREE_TEXT_HEADERS = new Set(['CONTAINER_NUMBER', 'CUSTOMS_CODES'])

const ID_ERROR_CODES = new Set(['MUST_BE_3_DIGIT_NUMBER'])

const ID_HEADERS = new Set(['OSR_ID', 'INTERIM_SITE_ID'])

const FIELD_RULES = [
  [CALCULATED_ERROR_CODES, CALCULATED_HEADERS, 'CALCULATED_FIELD_MISMATCH'],
  [PERCENTAGE_ERROR_CODES, PERCENTAGE_HEADERS, 'PERCENTAGE_FORMAT_INVALID'],
  [WEIGHT_ERROR_CODES, WEIGHT_HEADERS, 'WEIGHT_FORMAT_INVALID'],
  [DATE_ERROR_CODES, DATE_HEADERS, 'DATE_FORMAT_INVALID'],
  [YES_NO_ERROR_CODES, YES_NO_HEADERS, 'YES_NO_FORMAT_INVALID'],
  [DROPDOWN_ERROR_CODES, DROPDOWN_HEADERS, 'DROPDOWN_FORMAT_INVALID'],
  [FREE_TEXT_ERROR_CODES, FREE_TEXT_HEADERS, 'FREE_TEXT_INVALID'],
  [ID_ERROR_CODES, ID_HEADERS, 'ID_FORMAT_INVALID']
]

const GROUP_DISPLAY_CODES = new Map([
  ['FILE_DOWNLOAD_FAILED', TECHNICAL_ERROR_DISPLAY_CODE],
  ['FILE_REJECTED', TECHNICAL_ERROR_DISPLAY_CODE],
  ['FILE_UPLOAD_FAILED', TECHNICAL_ERROR_DISPLAY_CODE],
  ['VALIDATION_SYSTEM_ERROR', TECHNICAL_ERROR_DISPLAY_CODE],
  ['VALIDATION_FALLBACK_ERROR', TECHNICAL_ERROR_DISPLAY_CODE],
  ['UNKNOWN', TECHNICAL_ERROR_DISPLAY_CODE],

  ['FIELD_REQUIRED', 'DATA_ENTRY_INVALID'],
  ['INVALID_TYPE', 'DATA_ENTRY_INVALID'],
  ['VALUE_OUT_OF_RANGE', 'DATA_ENTRY_INVALID'],
  ['INVALID_FORMAT', 'DATA_ENTRY_INVALID'],
  ['INVALID_DATE', 'DATA_ENTRY_INVALID'],
  ['CALCULATED_VALUE_MISMATCH', 'DATA_ENTRY_INVALID'],

  // These fallbacks ensure a sensible message is shown even if a new header is
  // added to the backend without updating FIELD_RULES above...
  ['NET_WEIGHT_CALCULATION_MISMATCH', 'CALCULATED_FIELD_MISMATCH'],
  ['TONNAGE_CALCULATION_MISMATCH', 'CALCULATED_FIELD_MISMATCH'],
  ['UK_PACKAGING_PROPORTION_CALCULATION_MISMATCH', 'CALCULATED_FIELD_MISMATCH'],
  ['MUST_BE_A_NUMBER', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_A_STRING', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_A_VALID_DATE', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_GREATER_THAN_ZERO', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_AT_LEAST_ZERO', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_LESS_THAN_1', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_AT_MOST_1', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_AT_MOST_1000', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_AT_MOST_100_CHARS', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_YES_OR_NO', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_ALPHANUMERIC', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_3_DIGIT_NUMBER', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_VALID_EWC_CODE', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_VALID_RECYCLABLE_PROPORTION_METHOD', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_VALID_WASTE_DESCRIPTION', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_VALID_BASEL_CODE', 'DATA_ENTRY_INVALID'],
  ['MUST_BE_VALID_EXPORT_CONTROL', 'DATA_ENTRY_INVALID'],

  ['MATERIAL_REQUIRED', 'MATERIAL_INVALID'],
  ['MATERIAL_MISMATCH', 'MATERIAL_INVALID'],
  ['MATERIAL_DATA_INVALID', 'MATERIAL_INVALID'],

  ['REGISTRATION_REQUIRED', 'REGISTRATION_INVALID'],
  ['REGISTRATION_MISMATCH', 'REGISTRATION_INVALID'],
  ['REGISTRATION_DATA_INVALID', 'REGISTRATION_INVALID'],

  ['ACCREDITATION_MISSING', 'ACCREDITATION_INVALID'],
  ['ACCREDITATION_MISMATCH', 'ACCREDITATION_INVALID'],
  ['ACCREDITATION_UNEXPECTED', 'ACCREDITATION_INVALID'],

  ['HEADER_REQUIRED', 'STRUCTURE_INVALID'],
  ['TABLE_UNRECOGNISED', 'STRUCTURE_INVALID'],

  ['PROCESSING_TYPE_INVALID', 'TEMPLATE_INVALID'],
  ['PROCESSING_TYPE_MISMATCH', 'TEMPLATE_INVALID'],
  ['PROCESSING_TYPE_REQUIRED', 'TEMPLATE_INVALID'],

  ['SPREADSHEET_INVALID_ERROR', 'TEMPLATE_INVALID'],
  ['SPREADSHEET_MALFORMED_MARKERS', 'TEMPLATE_INVALID']
])

/**
 * Maps a backend validation errorCode (and optional column header) to a
 * display code used as an i18next key in `summary-log:failure.<displayCode>`.
 *
 * Resolution order:
 *  1. Field-level rules — matched when both errorCode AND header belong to a
 *     known pair (e.g. weight errors on weight columns). Checked in FIELD_RULES
 *     order; percentage is checked before weight because they share error codes.
 *  2. Group-level map — matched on errorCode alone for codes that share a
 *     single user-facing message (e.g. all technical errors → TECHNICAL_ERROR).
 *  3. Fallback — returns the raw errorCode, which either matches a direct
 *     en.json key (e.g. FILE_VIRUS_DETECTED) or triggers the i18next
 *     defaultValue (technical error message).
 * @param {string} errorCode - Backend validation error code
 * @param {string} [header] - Column header from `failure.location.header`
 * @returns {string} Display code for translation lookup
 */
export const getDisplayCodeFromErrorCode = (errorCode, header) => {
  const fieldMatch = FIELD_RULES.find(
    ([errorCodes, headers]) => errorCodes.has(errorCode) && headers.has(header)
  )

  if (fieldMatch) {
    return fieldMatch[2]
  }

  return GROUP_DISPLAY_CODES.get(errorCode) ?? errorCode
}
